import { State } from '@core/state';
export declare const Announcement: import("./models/announcement.model").AnnouncementModel;
export declare const Basis: import("./models/basis.model").BasisModel;
export declare const Comment: import("./models/comment.model").CommentModel;
export declare const Countdown: import("./models/countdown.model").CountdownModel;
export declare const Document: import("./models/document.model").DocumentModel;
export declare const Lottery: import("./models/lottery.model").LotteryModel;
export declare const Menus: import("./models/menus.model").MenusModel;
export declare const Player: import("./models/players.model").PlayersModel;
export declare const Questionnaire: import("./models/questionnaire.model").QuestionnaireModel;
export declare const Room: import("./models/room.model").RoomModel;
export declare const StreamView: import("./models/stream-view.model").StreamViewModel;
export declare const User: import("./models/user.model").UserModel;
export declare const Event: import("./models/event-emitter.model").EventEmitterModel;
export { State };
